<table class="leftNavMenu" width="150" cellspacing="1" cellpadding="1" border="1">
	<tr>
		<td><a href="/website/index.jsp">Home</a></td>
	</tr>
	<tr>
		<td><a href="/website/jsp/events.jsp">Events</a></td>
	</tr>
	<tr>
		<td><a href="/website/jsp/members.jsp">Members</a></td>
	</tr>
	<tr>
		<td><a href="/website/jsp/crescentgirls.jsp">Crescent Girls</a></td>
	</tr>
	<tr>
		<td><a href="/website/jsp/sports.jsp">Sports</a></td>
	</tr>
	<tr>
		<td><a href="/website/jsp/resources.jsp">Resources</a></td>
	</tr>
	<tr>
		<td><a href="/website/index.jsp">Item</a></td>
	</tr>
</table>	
